spring.application.name=next
spring.datasource.url=jdbc:mysql://localhost:3306/next
spring.datasource.username=root
spring.datasource.password=

# JPA / Hibernate
# 'update' is fine for learning, but remember to switch to 'validate' later
spring.jpa.hibernate.ddl-auto=validate

# Logging (Make it readable!)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
# Enable more detailed logging
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
logging.level.com.zaxxer.hikari.HikariConfig=DEBUG
logging.level.com.zaxxer.hikari=TRACE

# Optional: Shows the values of bind parameters (the ? in the query)
logging.level.org.hibernate.orm.jdbc.bind=TRACE