spring.config.import=optional:file:.env.local
spring.application.name=next
spring.datasource.url=jdbc:mysql://localhost:3306/test
spring.datasource.username=root
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
jwt.secret=JMqWXdd4Fw6tMENhyYU1YLHfVa6xHWOj3anmdltiLlTSYBjS9+vhjepV1rlj4FOu
jwt.expiration=3600000
logging.level.root=debug
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
# 'update' is fine for learning, but remember to switch to 'validate' later

# Logging (Make it readable!)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
# Enable more detailed logging
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
logging.level.com.zaxxer.hikari.HikariConfig=DEBUG
logging.level.com.zaxxer.hikari=TRACE

# Optional: Shows the values of bind parameters (the ? in the query)
logging.level.org.hibernate.orm.jdbc.bind=TRACE
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.security.web.access=DEBUG
