spring.config.import=optional:file:.env.local
spring.application.name=next
spring.datasource.url=jdbc:mysql://localhost:3306/next_ship
spring.datasource.username=next_dev
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
jwt.secret=JMqWXdd4Fw6tMENhyYU1YLHfVa6xHWOj3anmdltiLlTSYBjS9+vhjepV1rlj4FOu
jwt.expiration=3600000
logging.level.root=debug

# JPA / Hibernate
# 'update' is fine for learning, but remember to switch to 'validate' later

# Logging (Make it readable!)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Optional: Shows the values of bind parameters (the ? in the query)
logging.level.org.hibernate.orm.jdbc.bind=TRACE
